# Generated by Django 5.2.4 on 2025-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post.jpg', upload_to='post_images'),
        ),
    ]
