# Generated by Django 5.2.4 on 2025-12-16 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_bookmark_count_post_clap_count_post_love_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'post'], name='blog_reacti_user_id_9d08ac_idx'),
        ),
    ]
