# Generated by Django 5.2.4 on 2025-12-16 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_reaction_reaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_post_id_5fee65_idx',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', 'Love'), ('clap', 'Clap'), ('bookmark', 'Bookmark')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='blog_commen_post_id_0b6431_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='blog_commen_author__8d1ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_posted'], name='blog_post_date_po_b95ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='blog_post_author__038a48_idx'),
        ),
    ]
